# Generated by Django 6.1 on 2026-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['idempotency_key', 'created_at'], name='orders_orde_idempot_1123e6_idx'),
        ),
    ]
