# Generated by Django 6.1 on 2026-08-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('normalized_phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=20)),
                ('normalized_secondary_phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
