version: '3.9'
services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A config worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A config beat -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
