# Generated by Django 6.1 on 2026-08-14 11:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(choices=[('STEADFAST', 'Steadfast')], db_index=True, max_length=24)),
                ('external_order_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('consignment_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('tracking_code', models.CharField(blank=True, db_index=True, max_length=120)),
                ('delivery_status', models.CharField(db_index=True, default='CREATED', max_length=50)),
                ('cod_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'courier'), name='unique_order_courier_shipment')],
            },
        ),
    ]
